### ISSUE TITLE
Uses front instead of back camera

### ISSUE THREAD

**Issue by silverAndroid** [code-kotis/barcode-scanner#10]
Device: LG V20 
OS: Android 7.0 
 Chrome version: 55.0.2883.91

When the page loads, it uses my front facing camera as opposed to my back camera

**Comment by gokulkrishh** [comment]
@silverAndroid Can you clear your application storage in chrome and check again.

**Comment by silverAndroid** [comment]
It's still showing the front camera

**Comment by gokulkrishh** [comment]
@silverAndroid Issue is fixed. If you use the latest chrome it will work. Thanks
