### ISSUE TITLE
Code to stop scanner

### ISSUE THREAD

**Issue by AdijanDervisevic** [code-kotis/barcode-scanner#105]
Hi, 

first thanks to author for this great plugin, ti works perfect. Now i am just wondering if someone can help me with javascript code to stop scanning. I implemented it in popup and added button at top to close popup. I can hide popup with video inside, but in background browser is still accessing user webcam what causes website lagging so i would like to make 2 functions, one to StartScan and for StopScan.

**Comment by gokulkrishh** [comment]
@AdijanDervisevic Thanks!. Issues in GitHub are meant for issues in-app not for asking questions on how to make it work.

Pls, post your questions in StackOverflow to get help in coding. 

Quick help, [Check here](https://github.com/code-kotis/qr-code-scanner/blob/master/app/js/main.js#L51) for code.
