### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by TanQ10** [code-kotis/barcode-scanner#11]
Hi,

I am unable to build and deploy the project. I can get it up and running just fine though. I get this when i "npm run build". I did set the NODE_ENV var to production. I'm on Windows 10 Pro :(.

C:\Users\afrina\barcode-scanner>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\afrina\AppData\Roaming
asl.log=Destination=file
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-UAOTV7R
ComSpec=C:\WINDOWS\system32\cmd.exe
configsetroot=C:\WINDOWS\ConfigSetRoot
Git_SSH=C:\Program Files (x86)\PuTTY\plink.exe
HOMEDRIVE=C:
HOMEPATH=\Users\afrina
LOCALAPPDATA=C:\Users\afrina\AppData\Local
LOGONSERVER=\\DESKTOP-UAOTV7R
NODE_ENV=production
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\afrina\OneDrive
OS=Windows_NT
Path=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\PuTTY\;C:\Git\cmd;C:\MongoDB\Server\3.2\bin;C:\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Users\afrina\AppData\Roaming\npm;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3d04
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\afrina\AppData\Local\Temp
TMP=C:\Users\afrina\AppData\Local\Temp
USERDOMAIN=DESKTOP-UAOTV7R
USERDOMAIN_ROAMINGPROFILE=DESKTOP-UAOTV7R
USERNAME=afrina
USERPROFILE=C:\Users\afrina
windir=C:\WINDOWS

C:\Users\afrina\barcode-scanner>npm run build

> barcodeScanner@2.0.0 build C:\Users\afrina\barcode-scanner
> NODE_ENV=production webpack -p --config webpack.config.js && uglifyjs ./dist/decoder.min.js -c -m -o ./dist/decoder.min.js

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\afrina\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! barcodeScanner@2.0.0 build: `NODE_ENV=production webpack -p --config webpack.config.js && uglifyjs ./dist/decoder.min.js -c -m -o ./dist/decoder.min.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the barcodeScanner@2.0.0 build script 'NODE_ENV=production webpack -p --config webpack.config.js && uglifyjs ./dist/decoder.min.js -c -m -o ./dist/decoder.min.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the barcodeScanner package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack -p --config webpack.config.js && uglifyjs ./dist/decoder.min.js -c -m -o ./dist/decoder.min.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs barcodeScanner
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls barcodeScanner
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\afrina\barcode-scanner\npm-debug.log

**Comment by gokulkrishh** [comment]
@TanQ10 I see, issue is in `windows` the `NODE_ENV` is not recognized. Let me check if there a fix for it. Since I m working on mac.

**Comment by TanQ10** [comment]
I've been playing around with setting NODE_ENV to global, explicitly setting it to production, but i'm still having the same error.

**Comment by gokulkrishh** [comment]
@TanQ10 I tested in windows. NODE_ENV should be set properly to make it work. Try to set it again. Thanks
