### ISSUE TITLE
Did Not Connect: Potential Security Issue

### ISSUE THREAD

**Issue by hkalbasi** [code-kotis/barcode-scanner#112]
Firefox detected a potential security threat and did not continue to qrcodescan.in because this website requires a secure connection.

What can you do about it?

qrcodescan.in has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

**Comment by gokulkrishh** [comment]
@HKalbasi Thanks for reporting 👍 . There was an issue with SSL/TLS certificate. Its been resolved now. Let me know if you still face the issue else we can close this.

**Comment by hkalbasi** [comment]
Fixed. Thank you for quick response!
