### ISSUE TITLE
Issue scan QR in Iphone.

### ISSUE THREAD

**Issue by thanhbinh9xnt** [code-kotis/barcode-scanner#12]
I have to push source :https://github.com/code-kotis/barcode-scanner/tree/gh-pages to folder web in IIS 7.
It scan QR code in window phone and Android  is Ok , but at Iphone is not good.
i have to test in qrcodescan the same me.
you can support me, make it handle in iphone the same andoid and window phone?
sorry for my english not good!

**Comment by gokulkrishh** [comment]
@thanhbinh9xnt Hey, as of now `safari` doesnt support the `mediaStream API`. So for `iOS` [qrcodescan.in](qrcodescan.in) has a camera button on the bottom to take picture and scan the photo for qr codes. It should work fine. Let me know

**Comment by gokulkrishh** [comment]
Closing this issue. I mentioned the details in above comments. @thanhbinh9xnt Thanks
