### ISSUE TITLE
npm run start failed Failed at the barcodeScanner@2.0.0 start script 'webpack-dev-server --hot --inline --open'

### ISSUE THREAD

**Issue by nvbigben** [code-kotis/barcode-scanner#13]
G:\temp\pwa\barcodescanner\barcode-scanner>npm run start

> barcodeScanner@2.0.0 start G:\temp\pwa\barcodescanner\barcode-scanner
> webpack-dev-server --hot --inline --open

module.js:461
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:459:15)
    at Function.Module._load (module.js:407:25)
    at Module.require (module.js:487:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (G:\temp\pwa\barcodescanner\barcode-scanner\node_modules\webpack-dev-server\lib\Server.js:15:17)
    at Module._compile (module.js:560:32)
    at Object.Module._extensions..js (module.js:569:10)
    at Module.load (module.js:477:32)
    at tryModuleLoad (module.js:436:12)
    at Function.Module._load (module.js:428:3)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\nodejs\\node.exe" "c:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v7.0.0-nightly20160919366495d4e2
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! barcodeScanner@2.0.0 start: `webpack-dev-server --hot --inline --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the barcodeScanner@2.0.0 start script 'webpack-dev-server --hot --inline --open'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the barcodeScanner package,
npm ERR! not with npm itself.

**Comment by Sungdooyoo** [comment]
open package.json 

in line 16, you can find 

` "extract-text-webpack-plugin": "beta",`

change it to

` "extract-text-webpack-plugin": "latest",` 

or 

` "extract-text-webpack-plugin": "2.^0.0",` 

It seems the plugin doesn't support 'beta' version anymore

**Comment by e-sung** [comment]
Looks like 'webpack' hasn't properly installed.

Was `npm install` went fine with you? 

I changed line 16 of package.json 
from 
`"extract-text-webpack-plugin": "beta",` 
to
`"extract-text-webpack-plugin": "^2.1.0",`

And it fixed everything

**Comment by gokulkrishh** [comment]
#14 Fixed the issue. So closing it
