### ISSUE TITLE
npm run deploy failed

### ISSUE THREAD

**Issue by nvbigben** [code-kotis/barcode-scanner#15]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\nodejs\\node.exe" "c:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
npm ERR! node v7.0.0-nightly20160919366495d4e2
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! barcodeScanner@2.0.0 deploy: `npm run build && bash deploy.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the barcodeScanner@2.0.0 deploy script 'npm run build && bash deploy.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the barcodeScanner package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && bash deploy.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs barcodeScanner
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls barcodeScanner
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\temp\pwa\barcodescanner\barcode-scanner\npm-debug.log
[npm-debug.log.txt](https://github.com/code-kotis/barcode-scanner/files/845068/npm-debug.log.txt)

**Comment by gokulkrishh** [comment]
@nvbigben Not quite sure what's the issue here. is your `npm` and `node` path is correct ??

**Comment by gokulkrishh** [comment]
@nvbigben I guess the issue with the node or npm installation in your system. Try to install node again and try it. Thanks
