### ISSUE TITLE
Image Scanning not working in IOS or Iphone

### ISSUE THREAD

**Issue by nagesh1988** [code-kotis/barcode-scanner#16]
Following are the simulation steps,

1) I have taken snapshot in Iphone by Provided link from Application
2) Application looks, uploaded image scanning but no response even after 30 min.

Note:
 I have faced same problem with Zxing library & jsqrcode & qrcode-decoder-js. In case of taking snapshot from camera. Suspecting image size problem.

Awaiting for your reply.

**Comment by nagesh1988** [comment]
Any update guys...

**Comment by gokulkrishh** [comment]
@nagesh1988 I tested it in `iOS` both iPad & iPhone. Scanning doesnt work if the image is `too far`.

Can you post the image which you tested ??

**Comment by nagesh1988** [comment]
sure i can share. If i will take pic in mobile camera,its giving around 3MB to 4MB based on cam resolution or clarity. 
 I have seen one more plugin (https://bl.ocks.org/jazzido/9435670) almost similar to your application. It's giving quick response while web cam scanning but they didn't supported iPhone & Ipad. I mean camera approach.

Just for clarification I explained all these.  Following image you can check for testing.
![img_20170406_102137_1](https://cloud.githubusercontent.com/assets/4309524/24738477/9b95bc4c-1ab3-11e7-8bc9-427a8e49fb9b.jpg)

![image](https://cloud.githubusercontent.com/assets/4309524/24835081/5a5bd276-1d14-11e7-8f91-68ddcc5ad56c.png)


This image not working even in web level also.

This is sample. Similar kind only I am checking. Even I have tried different pics. But no luck.

Hope My information helps you to analyze the problem.

**Comment by nagesh1988** [comment]
Any update guys...

**Comment by gokulkrishh** [comment]
@nagesh1988 I tried these images in https://qrcodescan.in. I have no luck in making it work. 

But both of them works in android native app. I will try to find a solution for this. Will keep you posted.

Also from your feedback. I found out that, QR code scanning works for certain distance only when scanning via camera. Will try to address this as well. Thanks nagesh for your feedback.

**Comment by nagesh1988** [comment]
Thanks you for your quick response. 

I hope you can close this problem ASAP. I will also try on my end. If I will get any update I will share you.

Below plugin working with both the attached images, 

https://bl.ocks.org/jazzido/9435670

Thanks Once again.

**Comment by gokulkrishh** [comment]
@nagesh1988 Its working now. Updated the app. You will be able to scan now. Thanks
