### ISSUE TITLE
Scanning on iOS is a little clunky

### ISSUE THREAD

**Issue by mobile1za** [code-kotis/barcode-scanner#17]
I have tested the scanning feature on iOS devices and there are a lot of steps involved making it little clunky as follows:
Right now, the steps are
•        Click camera icon
•        click "take photo"
•        take the photo
•        click "use the photo"
•        Then if you do not take a clear photo of the code in a good position this whole process must be repeated. The guide for where the QR code needs to appear in the photo seems to disappear (same applies on Android.)

Is there a way to make it work where once you press the camera icon it just auto-scans without the need to take a photo first – like it works on Android. Is it possible to make automatically open the first URL it finds without displaying the pop-up message?

Thanks

**Comment by globophobe** [comment]
I believe that it will work like you want when Apple supports getUserMedia in Safari.

**Comment by gokulkrishh** [comment]
@globophobe Exactly!!

**Comment by mobile1za** [comment]
I see a relatively new blog from Webkit posted on Mar 29, 2017 which talks about new features in iOS 10.3. Some of the new features include HTML Media Capture. See this link - https://webkit.org/blog/7477/new-web-features-in-safari-10-1/

Is this what we're looking for?

**Comment by globophobe** [comment]
HTML Media Capture doesn't seem very useful for barcode scanning. It would be nice if Apple just supported getUserMedia.

**Comment by gokulkrishh** [comment]
@globophobe I agree. Lets hope apple implements the `getUserMedia` API soon enough.

**Comment by gokulkrishh** [comment]
@mobile1za Will add the camera API support once safari supports it. Thanks

**Comment by mobile1za** [comment]
It seems that support for the getUserMedia API is supported in preview as of 10 days ago. See https://w3c.github.io/mediacapture-main/

Does this mean it can be used now for this project?

**Comment by gokulkrishh** [comment]
@mobile1za Yes. Thats right. Have to wait for it to reach stable version (But i am planning to implement it soon). PR's are also welcome ;)

**Comment by mobile1za** [comment]
Great news! Can it be implemented before it reaches a stable version and does it have to be a stable version before it is released? How long does it usually take before it reaches a stable release?

**Comment by gokulkrishh** [comment]
@mobile1za Right now its in [safari 11 technology preview](https://developer.apple.com/safari/download/) which required `High Seirra` which in beta now. I will wait for it reach the stable `High Seirra`

**Comment by mobile1za** [comment]
I see that "Media Capture and Streams" is now Supported as per https://webkit.org/status/#specification-webrtc. Will you be making changes so this works on iOS without the need to take a photo now?

**Comment by gokulkrishh** [comment]
@mobile1za I will make the changes and will release the latest one soon. Thanks.
