### ISSUE TITLE
Unable to open camera

### ISSUE THREAD

**Issue by darkcyber** [code-kotis/barcode-scanner#19]
Hi, I just follow your tutorial then, I copy paste dist folder then upload in shared hosting.

When I run I got this error in the bottom left side

Unable to open camera. Provide permission to access camera.

How I can fix it?

Thanks.

**Comment by gokulkrishh** [comment]
@darkcyber Can you tell me which browser you are using ??

**Comment by darkcyber** [comment]
Chrome in Deepin OS not sure what version, and in Chrome 57 Windows.

You can try at http://surabayahackerlink.org/unmask-cyber-crime/qr/baca2/

**Comment by gokulkrishh** [comment]
@darkcyber Got the issue. Your site [`http://surabayahackerlink.org/unmask-cyber-crime/qr/baca2/`](http://surabayahackerlink.org/unmask-cyber-crime/qr/baca2/)  is running in `http`. `getUserMedia()` API which i am using in qrcode scanner requires `https` secure origin to work. Move your site to `https`. This will work.

**Comment by darkcyber** [comment]
@gokulkrishh How I can modify the script to work in http too? I just use this script for short time at this moment.

Thanks in advance.

**Comment by gokulkrishh** [comment]
@darkcyber No its not the script. Its `mediaStream API` which i am using for camera which will work only in secure origin.

**Comment by gokulkrishh** [comment]
@darkcyber Closing this issue for my above reason. Thanks.
