### ISSUE TITLE
Problems with npm run build

### ISSUE THREAD

**Issue by afcf23** [code-kotis/barcode-scanner#21]
Hello, 
The first command: **npm run start** it´s working very well but when i make this command : **npm run build** I have a problems with dist folder.

 I send you a image with the problem, bellow:

![problem](https://cloud.githubusercontent.com/assets/27778526/25191518/cadedf82-2527-11e7-9687-7d90d2f52f87.PNG)

Can you help me about this?

Best regards,
André Fernandes

**Comment by gokulkrishh** [comment]
@afcf23 Understood. Problem is with `ugligyjs` of `decorder.min.js`.

Replace the `build` in `package.json` with below and run it.

```bash
"build": "NODE_ENV=production webpack -p --config webpack.config.js
```

Uglify is not necessary, since it is already a minified file. I will remove that in next version. Thanks for reporting.

**Comment by afcf23** [comment]
Hello @gokulkrishh,
Thanks for your feedback.

I made that change in the project, however the command is not generating the dist folder as expected. There is no error logged when I run the command. 
So, I believe it might be related to another issue (maybe permissions ?). It shouldn't right?

Please let me know if I can share some image for you to help us to find the solution for this.

Thanks.
André

**Comment by gokulkrishh** [comment]
Hey @afcf23,

What is the error you are getting ?? `There is no error logged when I run the command`. Can you delete the folder and clone and run it again. Because the setup is fairly simple.

**Comment by afcf23** [comment]
Hello @gokulkrishh,

When I make this command "npm run build" I don't have errors. I see this on output only:

$ npm run build
> barcodeScanner@2.0.0 build C:\xampp\htdocs\barcode-scanner
> set NODE_ENV=production webpack -p --config webpack.config.js

Thanks,
André

**Comment by gokulkrishh** [comment]
@afcf23 So dist folder is not generated ??. May I know which OS you are using and node & npm version. I will try to debug it. THanks

**Comment by afcf23** [comment]
@gokulkrishh The dist folder was not generated.
OS - Windows 10 
Node: v6.10.2
npm: 3.10.10

Thanks

**Comment by gokulkrishh** [comment]
@afcf23 Cool. I will check it out and let you know.

**Comment by afcf23** [comment]
@gokulkrishh Do you have a news for me?

Thanks

**Comment by gokulkrishh** [comment]
@afcf23 Hey, ya i checked in windows 10 and all the npm and node path is set properly. Its works just fine for me.

**Comment by gokulkrishh** [comment]
@afcf23 Try to set up the node and npm path properly. It will work. Feel free to reopen if you have issue again. Thanks
