### ISSUE TITLE
Can it scan barcode ?

### ISSUE THREAD

**Issue by korrio** [code-kotis/barcode-scanner#22]
Or only QR code ?

**Comment by gokulkrishh** [comment]
@korrio It worked on both for me. You can test it let us know if there is any issue.

**Comment by gokulkrishh** [comment]
@korrio Let me know if you face any issue while scanning. Thanks

**Comment by CharlesOkwuagwu** [comment]
>  It worked on both for me. You can test it let us know if there is any issue.

@gokulkrishh Please which type of bar-codes were you able to scan?

**Comment by gokulkrishh** [comment]
@CharlesOkwuagwu It works with QR Code only. Library i am using support only QR Code.

**Comment by CharlesOkwuagwu** [comment]
> ZBar is an open source software suite for reading bar codes from various sources, such as video streams, image files and raw intensity sensors. It supports many popular symbologies (types of bar codes) including EAN-13/UPC-A, UPC-E, EAN-8, Code 128, Code 39, Interleaved 2 of 5 and QR Code.

@gokulkrishh 
I am able to scan both barcodes and QR-codes using this: https://gist.github.com/jazzido/9435670 which is base on https://github.com/yurydelendik/zbarjs, also derived from  `ZBar`
