### ISSUE TITLE
Help on MVC5

### ISSUE THREAD

**Issue by ginoburrr** [code-kotis/barcode-scanner#24]
Hi, im having trouble getting this working in ASP.NET MVC5.... 

Has anyone else managed to get it working in MVC5??

Thanks

**Comment by gokulkrishh** [comment]
@ginoburrr Yes the app will work with any framework. Its just a vanilla JS with a webworker file to decode the image and get qr code.

**Comment by gokulkrishh** [comment]
@ginoburrr Hope this answers you question. So closing it. Let me know if you need anything else. Thanks
