### ISSUE TITLE
It is failing at STEP 4 --npm run build

### ISSUE THREAD

**Issue by yousaid** [code-kotis/barcode-scanner#25]
Environment : Windows Pro.
Node: 6.10.0

> barcodeScanner@3.0.0 build C:\Users\yousaid\My Documents\barcode-scanner
> NODE_ENV=production webpack -p --config webpack.config.js

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! barcodeScanner@3.0.0 build: `NODE_ENV=production webpack -p --config we
bpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the barcodeScanner@3.0.0 build script 'NODE_ENV=production we
bpack -p --config webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the barcodeScanner packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack -p --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs barcodeScanner
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls barcodeScanner
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yousaid\AppData\Roaming\npm-cache\_logs\2017-05-15T23_17_14
_671Z-debug.log

**Comment by gokulkrishh** [comment]
@yousaid Try to set the proper node `NODE_ENV`. It will work. So closing this issue. Let me know if couldn't do it.
