### ISSUE TITLE
How do I use it in a static page?

### ISSUE THREAD

**Issue by sparksofire** [code-kotis/barcode-scanner#26]
Without use node

**Comment by gokulkrishh** [comment]
@wuxiaobo2014 Yes you can use it without node. Just copy the JS files and other files like images, css and other files like manifest etc and link it to index.html and add service worker if you want manually - follow this [demo-progressive-web-app](https://github.com/gokulkrishh/demo-progressive-web-app)

**Comment by sparksofire** [comment]
I am sorry for so long did not reply to you, I immediately try your program！And I am sorry for my poor English.

**Comment by gokulkrishh** [comment]
@wuxiaobo2014 Cool no issues 👍

**Comment by sparksofire** [comment]
Thanks for your comment,but I only want have a static page that have none server program and can scanner bacode and can use on part of Android equipment.

**Comment by gokulkrishh** [comment]
@wuxiaobo2014 Understood. You can use the https://rawgit.com/. RawGit serves raw files directly from GitHub with proper Content-Type headers. 

[Demo](https://cdn.rawgit.com/code-kotis/barcode-scanner/gh-pages/index.html)

**Comment by gokulkrishh** [comment]
@wuxiaobo2014 Also barcode-scanner is static site which doesnt involve any server expect to server the files via domain.

**Comment by sparksofire** [comment]
Ok!Thanks every much!

**Comment by gokulkrishh** [comment]
@wuxiaobo2014 I assume this fixes your issue. So closing this issue. Let me know if you need anything. Thanks
