### ISSUE TITLE
Not Scanning the QR code just shows the open and close buttons

### ISSUE THREAD

**Issue by ravimca49** [code-kotis/barcode-scanner#27]
i seen the demo web site  https://qrcodescan.in/
but i downloaded the code from the github .

i didn't seen the exact functionality.

i hosted your code in https://gunturstores.tk/bar/

Please check it

![image](https://cloud.githubusercontent.com/assets/6623815/26723985/b408289a-47b4-11e7-910c-17be53e7c965.png)

it shows like that

Please fix this issue as soon as possible.

I want the exact functionality in the https://qrcodescan.in/

**Comment by gokulkrishh** [comment]
@ravimca49 I dont' see any `script files` or `stylesheet` from qrcodescan.in and you can check `gh-pages` branch for `js` & `css` files. Add accordingly it will work. Closing it as its not an issue.

**Comment by ravimca49** [comment]
@gokulkrishh  Thank you so much. Yesterday i downloaded the master branch.
so it is not worked for me. As you said i downloaded the gh-pages now it's working fine in mobile device.
But in my Desktop showing the blank page. can you help me .what  is the problem.
Link is https://gunturstores.tk/finalq/

Thanks in advance.

**Comment by gokulkrishh** [comment]
@ravimca49 hi cool. Hey it's working fine for me in desktop. Clear your cache or check if you have blocked the camera permission or not. I think that's the issue.

**Comment by ravimca49** [comment]
@gokulkrishh Thank you so much for helping me.
now i cleared the cache in browser it's working perfect.

**Comment by ravimca49** [comment]
@gokulkrishh , This my Final Doubt Please clarify me.
I want to pass the decoded qrcode to another page in php, here i want do some functionality.
My doubt is How to stop showing the alert box after qrcode scans ?
Which event occurs to get the decoded qrcode data like this
`var decoded_data= $('#result').val();`

Please guide me.
Thanks in advance
