### ISSUE TITLE
How to Alert the QR Code data instead of showing the Dialog pop up

### ISSUE THREAD

**Issue by ravimca49** [code-kotis/barcode-scanner#28]
Hi,
I want to pass the decoded qrcode to another page in php, here i want do some functionality.

I tried this way 
`<div class="app__dialog app__dialog--hide">
          <div class="app__dialog-content">
            <h5>QR Code</h5>
            <input type="text" id="result"  onchange="display();">
          </div>
          <div class="app__dialog-actions">
            <button type="button" class="app__dialog-open">Open</button>
            <button type="button" class="app__dialog-close">Close</button>
          </div>
        </div>`

`function display(){
  var result = $("#result").val();
   alert(result);
}`

But it works after Qrcode scans  shows the decoded data on the input filed when ever i change the 
data in the dialog pop up then it alerts the data.

Here i need alert the decoded data after finishing the QR Scan instead of showing the pop up.
Then i can easily the forward the qrcode data to other pages.

Please guide me.
Thanks in advance

**Comment by gokulkrishh** [comment]
@ravimca49 This is where you will get the scanned QR code result [line 81](https://github.com/code-kotis/barcode-scanner/blob/master/app/js/main.js#L81). You can do what ever you want from here. Either to show a alert or dialog.

**Comment by ravimca49** [comment]
@gokulkrishh But i am not using the master branch code. I am using only **gh-pages** branch code.
Here there is no **main.js** file. Here **bundle.js** file is available.

**Comment by gokulkrishh** [comment]
@ravimca49 then bundle the application. Follow the master README.

**Comment by ravimca49** [comment]
@gokulkrishh  ok i will try.
But i failed in the first time because i am new to node js.

Thank you so much for clearing all my doubts

**Comment by gokulkrishh** [comment]
@ravimca49 👍

**Comment by gokulkrishh** [comment]
@ravimca49 Hope my answer resolved your questions. Closing this issue now. Thanks

**Comment by mengxin-FE** [comment]
> @ravimca49 This is where you will get the scanned QR code result [line 81](https://github.com/code-kotis/barcode-scanner/blob/master/app/js/main.js#L81). You can do what ever you want from here. Either to show a alert or dialog.

thanks a lot ，this point help me a lot ，just delete [line 76 ](https://github.com/code-kotis/qr-code-scanner/blob/master/app/js/main.js#L76)，dialog will disappear，and I can pass the result to another page。 

I find , if QRCode image size is small , it hard to scan. 

 in addition，could you please write more information about this project，I want to know it uses what blackmagic and how it works。sorry about that  I'm not familiar with webpack build project。
