### ISSUE TITLE
i can not use "npm run build" or "npm run "npm run deploy"

### ISSUE THREAD

**Issue by DannyWu2018** [code-kotis/barcode-scanner#29]
hi.
i click "npm run start" is ok, but npm run build , out error...
npm ERR!     NODE_ENV=production webpack -p --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs barcodeScanner
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls barcodeScanner
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-06-21T16_43_39_578Z-debug.log

what happen ?

**Comment by gokulkrishh** [comment]
@DannyWu2018 `NODE_ENV` is not working in windows. Have to change it to [cross-env](https://www.npmjs.com/package/cross-env) module to work everywhere.

**Comment by gokulkrishh** [comment]
@DannyWu2018 I have added `cross-env`. Can you check it and let me know ?

**Comment by gokulkrishh** [comment]
@DannyWu2018 I have tested it in linux and windows. Its working fine with cross-env. Hence closing this issue. Thanks for reporting.
