### ISSUE TITLE
No sw.js file loaded on our server - IOS Devices Run Issue

### ISSUE THREAD

**Issue by mihajlon97** [code-kotis/barcode-scanner#30]
We are trying to install your QRcode scanner, and succeed by Chrome and IE. Safari gives an error.

Here is your https://qrcodescan.in/ inspected scanner. 
![original](https://user-images.githubusercontent.com/23645296/27609391-e5aaebd2-5b8a-11e7-9b79-0b1930a0d726.png)
And so work good on IOS :
![whatsapp image 2017-06-27 at 21 22 54](https://user-images.githubusercontent.com/23645296/27609462-2189392e-5b8b-11e7-9974-9799b6de11f3.jpeg)

We have done everything as you said.
Works good on Chrome and IE, but on IOS (Safari) doesn't work
It looks so:
![whatsapp image 2017-06-27 at 21 35 16](https://user-images.githubusercontent.com/23645296/27609654-d7e9f618-5b8b-11e7-961d-86ed1e5bf3d2.jpeg)

Here is our inspected scanner.
![skizze](https://user-images.githubusercontent.com/23645296/27609557-7e4208da-5b8b-11e7-96c8-20df0b47c11f.png)

**So the difference is that by your scanner there are this sw.js and we don't have it**.

We have this sw.js on our server, but our scanner doesn't use it, and we don't know why.
Maybe is this issue.

Any solution?

**Comment by gokulkrishh** [comment]
@mihajlon97 `Service Workers` is not supported in iOS devices (safari, chrome etc,). More info [Webkit Status](https://webkit.org/status/#?search=service%20workers). But i have written code to upload or take picture and scan the QR code in iOS devices.

**Comment by alextappin** [comment]
Hi,

Any update on mediaCaptureStream for IOS? https://www.w3.org/TR/mediacapture-streams/

It looks like IOS now supports this. Any idea if this is possible to get working?

Also, looks like that link to the service workers is now supported.

**Comment by gokulkrishh** [comment]
@alextappin Yes we are working on adding support of media capture steam API in safari. There is some bug in showing the back camera via API. We will include it soon. Watch this issue for future info's.

**Comment by gokulkrishh** [comment]
@alextappin I tested the [qrcodescan](qrcodescan.in) app using media stream API. There are some issues with safari which prevents us from proceed further. Mentioning the issues below.

1. Not able show video stream without a small hack.
2. After adding the app to add to home screen, and opening it doesn't show video stream at all. This is another bug in safari. We will follow up with bugs to see if its fixed and then we can proceed further on this issue.

Thanks

**Comment by alextappin** [comment]
Thank you. I will be watching this project for updates.

**Comment by gokulkrishh** [comment]
@alextappin @mihajlon97 

Added the support for scanning the picture in iOS devices using mediaSteam API. But it has some limitations. Explained more in the PR

PR Link: https://github.com/code-kotis/barcode-scanner/pull/52. Just FYI guys. Since this is most asked feature for this app. Will close the issue once PR got merged.

**Comment by gokulkrishh** [comment]
Closing in favour of #52
