### ISSUE TITLE
Unable to open the camera, provide permission to access the camera

### ISSUE THREAD

**Issue by flaviomacias18** [code-kotis/barcode-scanner#33]
Hi.

I can not run the app on my phone.

The message "Unable to open the camera, provide permission to access the camera" appears.

How do I give permission on my cell phone?

**Comment by gokulkrishh** [comment]
@flaviomacias18 Clear cache your [qrcodescan](qrcodescan.in) site. And give it try

**Comment by flaviomacias18** [comment]
@gokulkrishh The problem is HTTPS. I was running on the HTTP server. Tks.

**Comment by gokulkrishh** [comment]
@flaviomacias18 Site will automatically redirect from **http** to **https**. Good to know 👍. Closing the issue now. Thanks
