### ISSUE TITLE
How to get it working on Iphone using Cordova

### ISSUE THREAD

**Issue by Shuliyey** [code-kotis/barcode-scanner#36]
Hi

Thanks for coming up with this great code.

I've been trying to get this packaged using cordova on android/iphone.

I managed to get it working perfectly on android

<dl>
  <img src="https://user-images.githubusercontent.com/4773348/32130175-f05ca480-bbde-11e7-8098-4d910cfa2fd9.jpeg" width="50%"></img>
</dl>

However on iphone it's experiencing difficulties (i understand iphone might work a little differently to android), basicly this is what's happening

* when the page load, it doesn't show the camera scan. I have to press `select from photos`,
* this will bring up the camera, which you can use to take photos, i took a photo and press `use Photo`
* the photo (that's taken) got pasted onto the scan screen, the app is trying to scan the photo that's taken, but nothing is happening from this point onward (i tried varies QR code photos). For some reason it doesn't seem to be recognising the QR code

<dl>
  <img src="https://user-images.githubusercontent.com/4773348/32130211-996cecc4-bbdf-11e7-8507-db9d05f1b398.jpeg" width="50%"></img>
</dl>

<dl>
  <img src="https://user-images.githubusercontent.com/4773348/32130216-af22cdea-bbdf-11e7-9bbe-06efd71bb2ce.jpeg" width="50%"></img>
</dl>

Just to confirm the expected behaviour on Iphone should be 

<dl>
  <img src="https://user-images.githubusercontent.com/4773348/32130222-dcffcf6a-bbdf-11e7-9992-082d6d9fbafe.jpeg" width="50%"></img>
</dl>

as this is the behaviour of android.

**Comment by gokulkrishh** [comment]
@Shuliyey Thanks for creating an issue for this. Safari didn't had [Media Capture and Streams](https://webkit.org/blog/7726/announcing-webrtc-and-media-capture/)  API support before, so taking picture and scanning it was the only way in iOS. I think it is supported now only in safari technology preview. I will add the similar behaviour like android once it is added to stable version (fallback as current in previous versions). 👍

**Comment by Shuliyey** [comment]
Thanks @gokulkrishh, nice exciting WebRTC support news in webkit. Just to confirm, when i take photoes and press use photoes in `ios` is it expected to work the same way as `android`, in my case i can see the scan picture, but system does not seem to recognise the qr code

<dl>
  <img src="https://user-images.githubusercontent.com/4773348/32130216-af22cdea-bbdf-11e7-9bbe-06efd71bb2ce.jpeg" width="50%"></img>
</dl>

**Comment by gokulkrishh** [comment]
@Shuliyey I agree it misses some qrcodes. Try taking it closeby. We have to wait till safari supports webRTC to add support similar to android. Thanks for feedback 👍

**Comment by Batur24** [comment]
@Shuliyey how do you make it work on cordova/android, could you show the code? Thanks!

**Comment by gokulkrishh** [comment]
Closing in favour of #52
