### ISSUE TITLE
Scan barcode formats supported by http://zbar.sourceforge.net/ such as code128

### ISSUE THREAD

**Issue by prasunsultania** [code-kotis/barcode-scanner#37]
why does the library supports only QR code despite the underlying library supports other formats as well ?

**Comment by gokulkrishh** [comment]
@prasunsultania I am using a basic QR Code scanner. Yes like you said updating the library will support other codes as well. I will try to update. Thanks for the feeback

**Comment by GokulDharumar** [comment]
@gokulkrishh Any updates on other barcode types esp code 39

**Comment by leroibeukes** [comment]
EAN 13 would be good ...

**Comment by gokulkrishh** [comment]
@leroibeukes @GokulDharumar Thanks for asking. For now I am planning to keep it as simple qr code scanner. But feel free to fork and change however you see fit your need.
