### ISSUE TITLE
How to use from .zip file

### ISSUE THREAD

**Issue by APdevelopments** [code-kotis/barcode-scanner#38]
HI,

Is it possible to use this in some projects? How can I simply upload all css, js files and try in the browser? Is that possible?

**Comment by gokulkrishh** [comment]
@APdevelopments Hey yes it is possible. Go to this branch [https://github.com/code-kotis/barcode-scanner/tree/gh-pages](https://github.com/code-kotis/barcode-scanner/tree/gh-pages) and download and upload. This branch contains css, js code like you asked.

**Comment by APdevelopments** [comment]
I try but won't work in the browser... I get just white screen
  
  https://www.screencast.com/t/IjmokMiFwcx7

**Comment by tedcampos** [comment]
the downloaded zip files are MISSING 2 files ++ a few lines of code.. UGH>>>

edit (index.html)
you must add: `<link href="bundle.css" rel="stylesheet">` to the header
and add: `<script type="text/javascript" src="bundle.js"></script>` just before the /body tag

also you must get these files (which were not included)
[https://qrcodescan.in/bundle.css](url)
[https://qrcodescan.in/bundle.js](url)

Also.. if your site is not located at the root of your domain, then you gotta remove the leading /slash from all of your reference links...
example:
change this >>>
`<link rel="shortcut icon" href="/images/touch/favicon.ico">`
to this>>>
`<link rel="shortcut icon" href="images/touch/favicon.ico">`

I hope this was helpful.. it took me forever to figure this crap out. ;)

**Comment by APdevelopments** [comment]
Can you please make jsfiddle

**Comment by gokulkrishh** [comment]
@APdevelopments You have to run in `local server` instead of opening the html file in browser.

**Comment by Shneory** [comment]
Hi, i'm succeeded to run it with a local server.
But how to make it work offline?
And why the file "bundle.js" in the site https://qrcodescan.in/ is only 5.5KB, and in localhost is 734KB?

**Comment by gokulkrishh** [comment]
Closing in favour of #52 and this is not a bug
