### ISSUE TITLE
how to make scan continues without refresing the page.. 

### ISSUE THREAD

**Issue by didikurnia** [code-kotis/barcode-scanner#39]
hello, can u help me to make this scan qrcode continously without refresh ?

i try to call the scan(); after app_dialog close. its not working...

**Comment by gokulkrishh** [comment]
@didikurnia Not sure why it is not working for you. I tested this scenario and its working fine for me. Give us some more inputs on how to re-produce this. Thanks

**Comment by gokulkrishh** [comment]
closing this as its I am not able to reproduce.
