### ISSUE TITLE
Not working in mobile browser (chrome)

### ISSUE THREAD

**Issue by aahedi** [code-kotis/barcode-scanner#4]
I had tried it but not working in mobile browser (chrome)

**Comment by gokulkrishh** [comment]
@aahedi Can you post the version of chrome and device info.

**Comment by aahedi** [comment]
chrome 50

**Comment by aahedi** [comment]
Chrome 50, Android 6.1

**Comment by gokulkrishh** [comment]
@aahedi Fixed in version 2 which is live now 👍
