### ISSUE TITLE
Uses front camera instead of rear

### ISSUE THREAD

**Issue by razorsoup** [code-kotis/barcode-scanner#40]
LG G6, Android 7.0, Chrome 64.0.3282.137

Front camera is used instead of the rear camera with no apparent way to swap it. This seems to possibly be a regression of issue #10.

**Comment by gokulkrishh** [comment]
@razorsoup Hmm. I will take a look into this. Thanks for reporting!

**Comment by gokulkrishh** [comment]
@razorsoup I checked. It seems like App is working on all the chrome version. Not sure why it didnt work for you. Closing this issue. Thanks for reporting.

**Comment by clinis** [comment]
I too have this problem. Already tried clearing application storage in Chrome and uninstalling the app.

LG G6, Android 8.0.0, Chrome version 67.0.3396.87, QR Scanner version 61

**Comment by gokulkrishh** [comment]
@clinis I see. I dont have LG g6 to test. If you guys have time pls let us know what's the issue. I checked in my android phone. Its working for me. See if it works for v68
