### ISSUE TITLE
Cannot install in Linux?

### ISSUE THREAD

**Issue by jeraldtc** [code-kotis/barcode-scanner#41]
Hi! Trying to run this on Linux and I encountered the following error on `npm run start`

> barcodeScanner@3.0.0 start /barcode-scanner
> webpack-dev-server --hot --inline --open
/barcode-scanner/node_modules/webpack-dev-server/bin/webpack-dev-server.js:4
const path = require("path");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! barcodeScanner@3.0.0 start: `webpack-dev-server --hot --inline --open`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the barcodeScanner@3.0.0 start script.
npm ERR! This is most likely a problem with the barcodeScanner package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --inline --open
npm ERR! You can get their info via:
npm ERR!     npm owner ls barcodeScanner
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-77-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "--harmony" "run" "start"
npm ERR! cwd /barcode-scanner
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /barcode-scanner/npm-debug.log
npm ERR! not ok code 0`

Is this a bug on Linux? Or Im doing something wrong?

Thanks!

**Comment by gokulkrishh** [comment]
@jeraldtc Hey can you check your node version, whether its stable one or not. Also i found some stackoverflow post on this, try following this and see if it solves your issue - https://stackoverflow.com/questions/36789889/syntaxerror-use-of-const-in-strict-mode 

Thanks for reporting!!

**Comment by jeraldtc** [comment]
Cannot update the node right now as there are other projects which still uses the same version. But I would probably install it on another server to test. Will update here if ever I get to setup a new server. Thanks!

**Comment by gokulkrishh** [comment]
@jeraldtc Sure 👍

**Comment by gokulkrishh** [comment]
@jeraldtc Since this is related to node version you are using. So closing this issue. Feel free to re-open if the issue exists again. Thanks
