### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [code-kotis/barcode-scanner#43]
I can’t access your website, please fix it.

**Comment by timvisee** [comment]
For me the website is reachable (and working).
Maybe it was temporarily offline, or you might have other personal networking issues.

I think this issue may be closed.

**Comment by gokulkrishh** [comment]
@KrasnayaPloshchad There is a issue with domain address. I will try to fix it soon. Thanks for reporting and @timvisee 👍

**Comment by gokulkrishh** [comment]
@KrasnayaPloshchad @timvisee Issue got fixed. So closing the PR. THanks 👍
