### ISSUE TITLE
Support SPARQCode

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [code-kotis/barcode-scanner#44]
SPARQCode is a matrix code encoding standard based on QR Code, including a convention for E-mail, Phone Number, WiFi and so on. The QR Code Scanner can show the detailed information in the dialog while got it, not just as plain text.
See: https://en.wikipedia.org/wiki/SPARQCode

**Comment by KrasnayaPloshchad** [comment]
The following sites can produce QR codes with SPARQCode:
http://goqr.me/
https://www.the-qrcode-generator.com/
http://protocoder.ru/firefox/Ultimate_QR_Generator

**Comment by gokulkrishh** [comment]
@KrasnayaPloshchad I hear you. We will look into the above links and figure out on this. Thanks for letting us know.

**Comment by gokulkrishh** [comment]
@KrasnayaPloshchad We have decided to keep it simple to support whatever qr code is we are supporting right now. If you want more, pls fork and do the changes.

We want keep it simple to showcase it as simple PWA. Hence closing this issue. Thanks!!
