### ISSUE TITLE
In IOS dont work

### ISSUE THREAD

**Issue by mangabr** [code-kotis/barcode-scanner#46]
Hi, i try to test live demo in IOS device and it dont work.
I managed to hit the photo and it appeared on the page, but did not occur scnner of the qrcode.

Iphone 5
IOS 11.4
Safari

**Comment by gokulkrishh** [comment]
@mangabr Okay thanks for reporting. We will look in the issue and try to fix it soon.

**Comment by lucasverra** [comment]
same on 11.4 for `iphone SE`

**Comment by NickHatBoecker** [comment]
No scanner at all. Have to click "Select from photo" then it displays the photo and the scannerline but no result is found.

iPhone SE, iOS 11.4 in Safari. Hope this helps. Really like the project!

**Comment by gokulkrishh** [comment]
@theskyliner Yes. There is media stream API similar to chrome in android now but there are some bugs which prevents us to implement. Watch this space for more updates. Thanks

**Comment by patrickpei** [comment]
What bugs? Happy to send a PR 😃

**Comment by gokulkrishh** [comment]
@patrickpei That would be great 👍   

Issues I found

1. media stream API wont work unless you have give a specific constraint for `mediaDevices.getUserMedia` API. Ref - https://github.com/gokulkrishh/tensorflow-find-object/blob/master/src/App.js#L64

2. After adding the app to home screen. Camera API is not working.

See if you can find a fix for these then we can add this API to the APP. Thanks again for asking @patrickpei

**Comment by gokulkrishh** [comment]
@theskyliner @mangabr @lucasverra I have created a PR to address the scanning feature in iOS devices. 

PR Link: https://github.com/code-kotis/barcode-scanner/pull/52. Just FYI guys. Since this is most asked feature for this app. Will close the issue once PR got merged.

**Comment by gokulkrishh** [comment]
Closing in favour of #52
