### ISSUE TITLE
Try it on local machine

### ISSUE THREAD

**Issue by Shneory** [code-kotis/barcode-scanner#48]
Hi,
I downloaded the zip file, and open it.
i'm open the folder "app" and click on the file "index.html"
and the page open without the camera. 
Can you help me with it, please?

Another thing, i want to use this code, are i need a special tools or i can edit it with notepad++?
Thanks

**Comment by gokulkrishh** [comment]
@Shneory App wont work unless you build it and use a local server. App is not a static page. Closing this issue. Hope this clarifies your doubt.

**Comment by Shneory** [comment]
Thank You for the answer.
I want to use the code only on the client side. I success to take the files "bundle.js" etc from the website, and its work for me. But I want to do some changes. Like, I want to start the camera with a button, and stop it when the decoder succeeded to decode the qr code.
What is the easy way to do that?

**Comment by gokulkrishh** [comment]
@Shneory Yes it is easy to do it. I have some methods to call scanning and all. Go through the code you will understand.

**Comment by Shneory** [comment]
Hi, I'm trying so much to build the code in node.js but its not working.
Did you have this code in version of fronted java script (in the client side), but not bundled, so i will can use it. or giving me more details how to building the code?

**Comment by gokulkrishh** [comment]
@Shneory What is the issue you are getting in NodeJS ??? Its working fine and details are given in readme file. Just a few commands nothing much.
