### ISSUE TITLE
Scanner does not work with Chrome version  67.0.3396.87

### ISSUE THREAD

**Issue by laoal11** [code-kotis/barcode-scanner#50]
The scanner does not seem to work anymore with the latest GoogleChromeupdate. 
All you get is the following warning: 
Invalid asm.js: Expected shift of word size decoder.min.js:43894 
Invalid asm.js: Expected shift of word size

For me, on my desktop Chrome version, all it shows is a black screen with the green bar going up and down.

**Comment by gokulkrishh** [comment]
@laoal11 Hey i am also using chrome v67 (In Mac) its working fine for me.

Like you said `Invalid asm.js: Expected shift of word size decoder.min.js:43894` - its a warning.

Trying clearing all the cache in application tab of chrome devTools. Let me know if it solve's your issue.

**Comment by laoal11** [comment]
Unfortunately it did not help. I am using Windows if that matters.

Ironically, the scanner works on my Samsung Galaxy XCover 3 on Chrome version 67.0.3396.87 on Android 6.0.1

**Comment by gokulkrishh** [comment]
@laoal11 Yep it does matters (Windows). Unfortunately i don't own a windows system. Would be great if I get some help from @hemanth or @shidhincr to figure this issue + to solve this https://github.com/code-kotis/barcode-scanner/pull/49

**Comment by laoal11** [comment]
I can test the app on my own Mac later today, I'll post an update then.

Update: The website works on my Mac on Chrome and Safari, both run on the latest version, weird.

**Comment by laoal11** [comment]
Update: Meanwhile it looks like this 
https://imgur.com/a/HaJ9t1h

Using Version 67.0.3396.87 still, I don't recall changing anything in my Chrome settings.

**Comment by gokulkrishh** [comment]
@laoal11 Thanks for testing it out. I tested in mac its working. Not sure why it is not working now. I didnt change the behaviour of it. Just added a fab button to take it from picture. I will check it out again. Need some test in iphones otherwise app is good to go.

**Comment by laoal11** [comment]
If you want I can test it on my iPhone 8. iOS and safari + chrome on latest versions.

**Comment by gokulkrishh** [comment]
@laoal11 That would be a great help. Pls keep us posted on the results. Thanks 👍

**Comment by gokulkrishh** [comment]
Closing in favour of #52
