### ISSUE TITLE
Problem Code Igniter 3X

### ISSUE THREAD

**Issue by jeanpablojp** [code-kotis/barcode-scanner#51]
All is working 100% from the examples but when i try to open the same code from a codeigniter project the camera opens OK, but the QRcode cant be found, i point to the QRCode but the javascripts dont fill the input. 
Any suggestions? 
I'm out of ideas anymore.
Thanks.

**Comment by gokulkrishh** [comment]
@jeanpablojp I m not sure what is the issue here. Try debugging and see if the scan method is called and web worker file is loaded or not.

**Comment by gokulkrishh** [comment]
@jeanpablojp This is not related to Barcode Scanner. Hence closing this issue. Pls take a look into code ignitor and fix this issue. Thanks for reporting.
