### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by elbazar** [code-kotis/barcode-scanner#56]
We have attempted to install the script several times. However, each time we have encountered the following error message.

"Error: pngquant failed to build, make sure that libpng-dev is installed"

Confirm that the mentioned node module is installed on the server. We have tested the installation via several different Node JS and NPM versions but each time the outcome was the same. 
Can you tell me what the solution to this problem is?

**Comment by gokulkrishh** [comment]
@elbazar May i know the version of OS, node, npm you are using and tried ??

If you are using linux based OS, google the error msg to get help.

`"Error: pngquant failed to build, make sure that libpng-dev is installed"`

Compatible node version is specified in the pkg.json file. It works in both `windows & osx`. If you still have the issue post it in stack over flow.  

Thanks!

**Comment by gokulkrishh** [comment]
@elbazar Closing this PR. Feel free to re-open if you still have this issue
