### ISSUE TITLE
Any way to stop QrReader.init() method

### ISSUE THREAD

**Issue by tag8ashok** [code-kotis/barcode-scanner#59]
Basically like to start and stop.(Toggle Button) After Scan i try again to call the same method but on the second try it isnt  working

**Comment by gokulkrishh** [comment]
@tag8ashok Could you explain more about exactly what you did ?

**Comment by tag8ashok** [comment]
I created a button called scan which called a function which contains the statement QrReader.init() that working properly on the close button i m trying to get back to page containing the scan button on clicking scan again the scanner element is visible but unable to scan any  QR. I have checked using breakpoints its reaching upto line 91 containing the scan and unable to execute further.

**Comment by gokulkrishh** [comment]
@tag8ashok Seems like you are trying to do something specific. Pls go through code again and understand how scan is happening and do it. Closing this as its not an issue.
