### ISSUE TITLE
Won't work on iPhone, how can i fix it?

### ISSUE THREAD

**Issue by JochemATN** [code-kotis/barcode-scanner#6]
I build this script in a website, but it works on Android (Google Chrome), but not on iPhone (all browsers, tested in Safari, Firefox and Chrome). Can you tell me how do i fix this?

**Comment by gokulkrishh** [comment]
Hi @JochemATN Its because there is no API support in iOS. See [here](http://caniuse.com/#search=getUserMedia). As of now we have to wait for the API implementation from iOS side

**Comment by gokulkrishh** [comment]
I guess this addresses your question @JochemATN

**Comment by JochemATN** [comment]
Thanks for your fast reaction. but is a pitty that's not supported... Do you know a way how i can build a script that scans QR-codes what is supported by Adroid as well iOS? I want to build a webshop with a search-function on the mobile website who is supported this function.

**Comment by gokulkrishh** [comment]
Ohh @JochemATN You can use the same script I have used in this app. But as for iOS not sure when they will give API support. You can check their development process [here](https://webkit.org/status/) as in which feature is under development or under consideration etc..

**Comment by JochemATN** [comment]
But if i run your app on my iphone there happens nothing? how does that come? I am not that experienced developer... sorry!

**Comment by gokulkrishh** [comment]
@JochemATN Not sure what you are trying to say!!

**Comment by JochemATN** [comment]
I run your app in Safari on iOS 10 but there will show no camera? I am not an very experienced programmer. Can you give me an example of how do i get your code working on my iphone, or is this not supported yet?

**Comment by gokulkrishh** [comment]
@JochemATN Again, its not supported yet. Check the link I gave you above.!!

**Comment by JochemATN** [comment]
Ah, now i understand. Sorry my english is not that good.

**Comment by JochemATN** [comment]
Thanks! =)

**Comment by PaulKinlan** [comment]
@gokulkrishh just as a quick FYI, I got QR Code scanning working on iOS by launching the camera app and processing the result.  It's not exactly the same but it works.

Code: https://github.com/PaulKinlan/qrcode
Demo: https://qrsnapper.appspot.com/
Docs: https://developers.google.com/web/fundamentals/native-hardware/capturing-images/

**Comment by gokulkrishh** [comment]
@PaulKinlan Thanks for letting me know 👍 I will check it out.

**Comment by gokulkrishh** [comment]
@JochemATN check the above comments for iOS implementation.
