### ISSUE TITLE
Support for PDF417

### ISSUE THREAD

**Issue by DeanWilliamMills** [code-kotis/barcode-scanner#60]
I tried scanning a PDF417 barcode, but it's not scanning the barcode. Will it be possible to add PDF417 format?

**Comment by gokulkrishh** [comment]
@DeanWilliamMills No. Its only a QR code scanner. I guess name of the repo is confusing for many people. I will change it to qrcode scanner. 

If you want to support other formats pls fork and do the changes you required. THanks
