### ISSUE TITLE
Unable to deploy on Heroku

### ISSUE THREAD

**Issue by AshokNaik009** [code-kotis/barcode-scanner#61]
What  changes need to be made in order to deploy this application on heroku

**Comment by gokulkrishh** [comment]
@AshokNaik009 What are the steps you followed. All you need to do it `npm run build` and it will give you build folder. Move it to `heroku` or any deployment service.

**Comment by AshokNaik009** [comment]
First cloned this repo  then npm install and i also tried npm run build then 
heroku git:clone -a qrpwa
 git add .
 git commit -am "make it better"
 git push heroku master.

**Comment by gokulkrishh** [comment]
@AshokNaik009 Output build is in the `dist` folder. Its straight forward `npm install` -> `npm run build` and push the `dist folder` to heroku. Closing this. As its not a issue with app. Post your questions in stackoverflow to get help for heroku.
