### ISSUE TITLE
iOS Camera Access when used as PWA

### ISSUE THREAD

**Issue by mechko** [code-kotis/barcode-scanner#62]
Cool app with cool approach, thanks so far! I'm on iPhone 7 and iOS 12.1 and not sure if this is an issue, I've done  the following steps: 

- opened https://qrcodescan.in/ in Safari
- app asked for Camera access, approved
- QR-Code Scanning works so far from Safari

- then I used the "Share Menu" at the bottom menu of Safari and selected "Add to home screen"
- the App was added to my home screen
- opened the PWA using the new QR icon on home screen
- splash screen with QR Logo is shown 
- then there is only a grey background and the "plus photo icon" (and the Info button at the upper right corner), so live scanning is not working
- using the plus-photo icon the "manual" photo processing is working

Can I do something about the camera access settings for this PWA, or is this an known issue on iOS? Happy to hear from you, thanks again!

**Comment by gokulkrishh** [comment]
@mechko Thanks for reporting 👍in detailed way.

To answer your question..

- When launching the app from homescreen in iOS devices, app will be launching from webkit webview which doesn't support mediaStream API. Same goes for service worker.

We have to wait for apple to update the safari to allow camera access. Hence we added a 'plus photo icon' to manually scan the pics.

More: https://github.com/code-kotis/qr-code-scanner/pull/52

**Comment by mechko** [comment]
Okay, I see. Thanks for the reply, lets hope Apple is adding this very soon.
