### ISSUE TITLE
Different colors in QR code

### ISSUE THREAD

**Issue by TJHoekstra** [code-kotis/barcode-scanner#63]
Hi,

The demo works fine when QR code is black with a white background. But for example white on a dark green background does not work. Tested on iOS 12.1 in Safari.

Is is possible to support other colors?

Thank you

**Comment by gokulkrishh** [comment]
@TJHoekstra Not sure this is supports out of box or not. Need to check if we can support it. Will keep you posted on this. Thanks!!

**Comment by KrasnayaPloshchad** [comment]
There are several online QR code generators can produce QR codes with different colors, so you'll easy to get that if you want a test case.
https://www.qrcodes-generator.com/
https://www.qrcode-generator.ch/?lang=en

**Comment by gokulkrishh** [comment]
@KrasnayaPloshchad Sure. Thanks. I will check. @TJHoekstra As of now planning to keep it this way. But PR's are welcome.

**Comment by gokulkrishh** [comment]
Closing this. As for now planning to keep it simple pwa.
