### ISSUE TITLE
Integrate with Angular/IONIC?

### ISSUE THREAD

**Issue by fransyozef** [code-kotis/barcode-scanner#67]
Is it possible to use this in Angular / IONIC (PWA)?

**Comment by gokulkrishh** [comment]
@fransyozef Yes. It is possible. Since its written in vanilla js :D. Feel free to fork and play with it.

**Comment by fransyozef** [comment]
hmm .. you don't happen to have an example

**Comment by gokulkrishh** [comment]
@fransyozef Sorry I dont have. Go through the code. Its simple.

Closing this issue. Feel free to reopen if needed

**Comment by iamsank8** [comment]
Please make an Angular Example
