### ISSUE TITLE
Install help please

### ISSUE THREAD

**Issue by gheeenrique** [code-kotis/barcode-scanner#68]
Hi, sorry for the question.
Is it possible to install on cpanel server?
I did the installation but I can not open the camera in the browser, and I also can not get mobile.
Follow URL: https://cupom.idelhost.com.br/qr-code-scanner-master/app/

**Comment by gokulkrishh** [comment]
@gheeenrique Hey, sure. I check your URL.

Site is missing stylesheet as well [main.bundle.js](https://qrcodescan.in/main.201113f887d44acdfa77.bundle.js). Add this it will work. Hope this helps.
