### ISSUE TITLE
 I am only able to access the front camera no options for rear camera

### ISSUE THREAD

**Issue by shah-pooja** [code-kotis/barcode-scanner#69]
Please provide me some solution regarding how to access the rear camera for reading the QR code. I have implemented this in PWA. It only opens in front camera.

**Comment by shah-pooja** [comment]
Though I have upgraded my chrome version to the latest it is still not showing me the rear camera.

**Comment by gokulkrishh** [comment]
@shah-pooja Try following this approach https://github.com/gokulkrishh/tensorflow-find-object/blob/master/src/App.js#L28

**Comment by bilogic** [comment]
@gokulkrishh can you elaborate a little bit more? I also only see the front camera on my Samsung A50 running on Android PIE. Thank you.

**Comment by gokulkrishh** [comment]
@bilogic I dont remember this works. As i dont own a android anymore. But try to implement the logic in above link from 

Line no: https://github.com/gokulkrishh/tensorflow-find-object/blob/master/src/App.js#L39
To Line no: https://github.com/gokulkrishh/tensorflow-find-object/blob/master/src/App.js#L71

It should work.

**Comment by gokulkrishh** [comment]
Feel free to reopen if needed.

**Comment by yllihyseni** [comment]
qrscan.js

Replace:
https://github.com/code-kotis/qr-code-scanner/blob/98a0dd4af1b46cc9a32d1db9df048a6db62ecc6f/app/js/vendor/qrscan.js#L88

With:
`sourceId: device[device.length-1].deviceId ? device[device.length-1].deviceId : null`
