### ISSUE TITLE
media device not found

### ISSUE THREAD

**Issue by shah-pooja** [code-kotis/barcode-scanner#71]
Is there any possibility to detect the media devices proactively or to show the message that QR code scanning cannot be supported on desktop. I am also facing issues while scanning the QR code with the webcam attached.
It gives me the following error:

_ERROR Error: Uncaught (in promise): NotFoundError: Requested device not found_
 _Error: Uncaught (in promise): OverconstrainedError: {}_

**Comment by gokulkrishh** [comment]
@shah-pooja I am not sure how to help you here. I haven't tried it with web-cam. So need no idea on how to make it work with web cam.

**Comment by gokulkrishh** [comment]
@shah-pooja post your questions in stackoverflow. This is not a helping forum
