### ISSUE TITLE
scanner not working in ios device

### ISSUE THREAD

**Issue by shah-pooja** [code-kotis/barcode-scanner#72]
Hi there. I am having problems using this package with ios devices. It does not work for google chrome in ios device at all. It works in safari but only accesses the camera that to camera gets stuck after allowing permission.

**Comment by gokulkrishh** [comment]
@shah-pooja Hi, Google chrome in iOS is just a wrapper for webkit webview. Meaning it is version of safari which doesn't have access to camera. So you need the use [qrcodescan.in](qrcodescan.in) in safari app.

**Comment by gokulkrishh** [comment]
Closing the issue!. Hope i have answered your question.
