### ISSUE TITLE
Please help me install

### ISSUE THREAD

**Issue by xiaxiao001** [code-kotis/barcode-scanner#73]
Hello, I may need a complete example and documentation, I need to use it on the vue project.
However, I can't run it when I test it locally.

**Comment by gokulkrishh** [comment]
@xiaxiao001 Instruction for how to run it is given in readme. It should work.

**Comment by gokulkrishh** [comment]
@xiaxiao001 Post your questions in stackoverflow and issues in github are meant for issues in app.
