### ISSUE TITLE
iOS WebView workaround not working

### ISSUE THREAD

**Issue by mfulton26** [code-kotis/barcode-scanner#78]
I see that for iOS I can take a video or photo using the camera as the live user media stream is not available in Chrome for iOS nor in the PWA one added to the home screen from Safari. This seems like a good workaround but I cannot get it to work with a static video or photo.

e.g. I tested on an apple juice bottle with a smartlabel QR code:

http://smartlabel.coca-colaproductfacts.com/servlet.MinuteMaid-JuicesToGoAppleJuice-1PK-1000-oz-Label-PET-Bottle-025000056765.html

![image](https://user-images.githubusercontent.com/5588957/67767495-affbfa00-fa1e-11e9-98c6-e921ad9acff8.jpg)

**Comment by gokulkrishh** [comment]
@mfulton26 Yes. Seems like its a bug. I am also not able to make it work. I will try it. Thanks for reporting

**Comment by gokulkrishh** [comment]
@mfulton26 Hi, Just wanted to let you know in IOS 13.4 verision, webkit webview (ADD to home screen) allows camera API. It works.

**GIF**:

![ezgif-3-d79e698710d2](https://user-images.githubusercontent.com/2944237/77603660-a24b9180-6f36-11ea-8335-d568662b39c0.gif)

Thus closing this issue. Feel free to re-open.

**Comment by mfulton26** [comment]
that must be new, thank you
