### ISSUE TITLE
not working in mobile browser

### ISSUE THREAD

**Issue by sunnysharma03** [code-kotis/barcode-scanner#8]
when I'm trying to open it with my Microsoft Lumia it is giving me error : Unable to open the camera, provide permission to access the camera.
But I'm allowing it to access the camera

**Comment by gokulkrishh** [comment]
@sunnysharma03 Probably an API support is not in Lumia. Which browser is it?? I couldn't test it Lumia. Will look into it. Thanks for reporting!!

**Comment by gokulkrishh** [comment]
@sunnysharma03 Hi could you give us some more details about your browser, OS version etc.

**Comment by sunnysharma03** [comment]
I'm using windows 10 in my lumia and browser is Edge

**Comment by gokulkrishh** [comment]
@sunnysharma03 Thanks. Will look into it.

**Comment by gokulkrishh** [comment]
@sunnysharma03 Now works in Edge as well. So closing this. If issue is still there. Feel free to reopen this issue.
