### ISSUE TITLE
iOS installed app doesn't use camera

### ISSUE THREAD

**Issue by comatory** [code-kotis/barcode-scanner#80]
When on iOS in Safari, I get prompt to use camera and the app works fine. However when I add it to home screen I do no get the prompt and the screen just stays grey:

![IMG_E8276716818C-1](https://user-images.githubusercontent.com/5990424/68371591-5478ed00-013f-11ea-88cd-579b9ee0bd29.jpeg)

When I try to use the button in lower right to take the photo, it can't "scan" the QR code from the photo:

![IMG_14F4F3420DD5-1](https://user-images.githubusercontent.com/5990424/68371638-678bbd00-013f-11ea-8ac2-5c922bc68cbf.jpeg)

Is this iOS limitation? Works well in the Safari browser on iOS though.

**Comment by caesss** [comment]
same issue here, any updates?

**Comment by gokulkrishh** [comment]
@caesss @comatory Keep a 👁 on this [bug tracker](https://bugs.webkit.org/show_bug.cgi?id=185448). Once webkit team resolves it. It will automatically work without any change.

**Comment by gokulkrishh** [comment]
@caesss @comatory Hi, Just wanted to let you people know in IOS 13.4 verision, webkit webview (ADD to home screen) allows camera API. It works.

**GIF**:

![ezgif-3-d79e698710d2](https://user-images.githubusercontent.com/2944237/77603660-a24b9180-6f36-11ea-8335-d568662b39c0.gif)

Thus closing this issue
