### ISSUE TITLE
Unable to access camera on mobile browser while this application is deployed on Linux server

### ISSUE THREAD

**Issue by ashishurfriend008** [code-kotis/barcode-scanner#83]
Hi ,

Please be informed, while i access the public URL on mobile browser the camera could not able to detect while this application is deployed on Linux server.

Could you please help me how to deploy this application over Linux server and can able to access camera scanner on mobile devices.

Regards,
Ashish

**Comment by gokulkrishh** [comment]
@ashishurfriend008 Issues in github are meant for issues in app. This is not a helping forum. pls post your questions in stackoverflow.
