### ISSUE TITLE
possible bug with URLs

### ISSUE THREAD

**Issue by earwickerh** [code-kotis/barcode-scanner#87]
When I scan a qr for a non- http:// URL, I don't get the "open" button. However if I first go to an http url->tap "close" -> then go to a non http:// url the "open" button shows up. Using firefox on android.

p.s. Great App! Thank you!

**Comment by gokulkrishh** [comment]
@earwickerh Seems like a BUG 🐞. Thanks for reporting. I will check the issue.

**Comment by gokulkrishh** [comment]
@earwickerh I am not able to reproduce this issue. It works fine for both http, https url. Closing the issue for now. Feel free to re-open if needed!
