### ISSUE TITLE
not working on iphone

### ISSUE THREAD

**Issue by khushi4** [code-kotis/barcode-scanner#9]
I was trying to open the live url: https://qrcodescan.in/ on iphone chrome and safari browser.
But camera is not opening.

I tried that source code also, but facing the same problem.

**Comment by gokulkrishh** [comment]
@khushi4 https://qrcodescan.in/ now supports iOS. Check it out. Thanks for filing the issue!!

**Comment by nagesh1988** [comment]
Supports but only works for smaller size images. For snapshots from camera directly, QR code scanning not working. If we upload manually from gallery smaller image, QR code scanning working.

Kindly suggest some alternative to overcome this issue. Awaiting for your response.
