### ISSUE TITLE
Use front camera only

### ISSUE THREAD

**Issue by NoverNobida** [code-kotis/barcode-scanner#92]
**Describe the bug**
On samsung mobile phone, the application uses only the front camera.

**Smartphone (please complete the following information):**
 - Device: [Samsung S10]
 - OS: [oneui 2.0]
 - Browser [kiwibrowser and default browser]
 - Version [latest]

**Comment by offsui** [comment]
I have the same Issue.

Galaxy S20+
Chrome and Samsung Browser
Newest Android Version 10 (UI 2.1)

(On my Old Galaxy S9+ it has worked)

Any Solutions?

**Comment by Messaoudi-Nagib** [comment]
Same issue on a Galaxy s10+ with Android 10 too.

**Comment by gokulkrishh** [comment]
@Messaoudi-Nagib @offsui @NoverNobida Thanks for reporting. I will look into it. 

Issue seems like latest chromium based browsers are loading front camera instead of back camera.

**Comment by gokulkrishh** [comment]
@NoverNobida @offsui @Messaoudi-Nagib Hi, I have tested the app in android 10 and latest chrome. It opens back camera only. Not the front. Not sure how to reproduce it.

**Comment by offsui** [comment]
@gokulkrishh But with which Phone? I think it is **Phone depending**. With my Huawei Mate 20 Lite it has worked, also with Android Version (9.0) and Chrome (80.0.3987.132).

**Comment by gokulkrishh** [comment]
@offsui Yes it worked in android 10 and latest chrome. 

But in samsung browser and chrome browser in samsung smartphone, camera opened is front not rear.

**Comment by offsui** [comment]
@gokulkrishh possible to fix this?

**Comment by offsui** [comment]
@gokulkrishh hm?

**Comment by gokulkrishh** [comment]
@offsui Hi, Sorry for late reply. I dont have samsung device to verify my changes. Perhaps you can send a PR?

**Comment by offsui** [comment]
@gokulkrishh where can i try it?
Sorry for my question, what is "PR"?

**Comment by gokulkrishh** [comment]
@offsui  Sure no problem. [Start here](https://github.com/code-kotis/qr-code-scanner/blob/master/app/js/vendor/qrscan.js#L76)

`PR` = `Pull Request` (Fix for this issue)

**Comment by offsui** [comment]
@gokulkrishh The Last change of this File was on 15 Oct 2018 ? https://qrcodescan.in still doesn't work with Galaxy Phone (Front Cam is used). Sorry I don't know what to do ?

**Comment by gokulkrishh** [comment]
@offsui Hi, as of now i am not planning to fix it. I have added help wanted. I will post in twitter and see if anybody is ready to fix this.

**Comment by gokulkrishh** [comment]
This is fixed in #94 so closing it
