### ISSUE TITLE
It ask for user pass

### ISSUE THREAD

**Issue by mrzhoul-2** [code-kotis/barcode-scanner#96]
i just apt install npm
sudo npm update
su
git clone
npm install
npm update again
npm run start
npm run build
npm run deploy

last command run deploy... it ask for user pass for github. after that it says...

Rewrite a403c8677c0f576bc344b3bafd8be3768037e5b4 (13/13) (0 seconds passed, remaining 0 predicted)
Ref 'refs/heads/gh-pages' was rewritten
Username for 'https://github.com': mrzhoul-2
Password for 'https://mrzhoul-2@github.com': 
remote: Permission to code-kotis/barcode-scanner.git denied to mrzhoul-2.
fatal: unable to access 'https://github.com/code-kotis/barcode-scanner/': The requested URL returned error: 403
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

What the problem exactly?

**Comment by gokulkrishh** [comment]
@mrzhoul-2 Issue are meant for issues in application and its not a help forum. Post your questions in stackover flow.

And regarding your question. Of course you dont have access to the project so you cannot deploy it.
