### ISSUE TITLE
 The error you provided does not contain a stack trace

### ISSUE THREAD

**Issue by AKclown** [code-kotis/barcode-scanner#98]
index.js:1 Uncaught Error: The error you provided does not contain a stack trace.
    at S (index.js:1)
    at V (index.js:1)
    at index.js:1
    at index.js:1
    at a (index.js:1)
S @ index.js:1
V @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
a @ index.js:1
:3000/#/:1 Uncaught (in promise) DOMException: Requested device not found

**Comment by gokulkrishh** [comment]
@AKclown Provide more information. When did you got the issue and on what device?

**Comment by AKclown** [comment]
I reported this error during initialization

**Comment by AKclown** [comment]
![image](https://user-images.githubusercontent.com/33648653/81392864-e0e98400-9151-11ea-9cac-afc82df1b3ce.png)
![image](https://user-images.githubusercontent.com/33648653/81392890-ea72ec00-9151-11ea-8532-5cc53decdd0c.png)
![image](https://user-images.githubusercontent.com/33648653/81392903-f199fa00-9151-11ea-8d78-3a12e5aa76cf.png)

**Comment by AKclown** [comment]
![image](https://user-images.githubusercontent.com/33648653/81392940-07a7ba80-9152-11ea-8f32-2e1a0c5022be.png)

**Comment by AKclown** [comment]
import QRScanner from 'qr-code-scanner';

**Comment by AKclown** [comment]
import QRScanner from 'qr-code-scanner';

 async componentDidMount() {
        QRScanner.initiate({
            onResult: (result) => { console.log('测试'); },
            timeout: 10000
        });
}

I only added these two sentences in react。He made a mistake

**Comment by AKclown** [comment]
My local environment here, not https

**Comment by gokulkrishh** [comment]
@AKclown Hi, this is not a npm module where you can install it and use it. Its a simple web app.

closing this issue as this is not an issue. Pls post your questions in stackover flow to get help.

**Comment by AKclown** [comment]
thanks  you 。  I found the same name at npm and thought your
