### ISSUE TITLE
Not working in chrome ios

### ISSUE THREAD

**Issue by TrackMyToken** [code-kotis/barcode-scanner#99]
**Describe the bug**
I see a blank screen when I opened qrcodescan.in in chrome ios.

**To Reproduce**
1. Go to https://qrcodescan.in in chrome ios
2. We see a blank screen

**Expected behavior**
It should as for permissions to access camera and should be able to scan

**Smartphone (please complete the following information):**
 - Device: all the iphones
 - OS: IOS
 - Browser : chrome
 - Version : latest(I am wring this on May 10th, 2020)

**Comment by gokulkrishh** [comment]
@TrackMyToken 

Yes this web app will not work in any iOS browsers except safari browser. 

Chrome in iOS is made of iOS WebKit. iOS WebKit doesnt provide access to API's. Hence it will not work in ios third party browsers. 

Closing this issue as it cannot be fixed from our side.

More ans: https://stackoverflow.com/questions/51501642/chrome-and-firefox-are-not-able-to-access-iphone-camera?answertab=active#tab-top
